// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetConfigDir():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetDefaultConfig():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function ListBackups():Promise<Array<main.BackupInfo>>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function ValidateConfig(arg1:string):Promise<void>;
